# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

right_format = '$time'

palette = "rose-pine"

[palettes.rose-pine]
overlay = '#26233a'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ebbcba'
pine = '#31748f'
foam = '#9ccfd8'
iris = '#c4a7e7'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[time]
disabled = false
format = '[$time 󰧱]($style)'

[directory]
truncation_length = 6
truncation_symbol = '…/'
format = '[󰉊 $path]($style)[$read_only]($read_only_style) '
